package com.eramaya.eravett.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Agency generated by hbm2java
 */
@Entity
@Table(name="agency"
    ,schema="eravett"
)
public class Agency  implements java.io.Serializable {


     private Integer agencyId;
     private String name;
     private Set<VettingStatus> vettingStatuses = new HashSet<VettingStatus>(0);

    public Agency() {
    }

    public Agency(String name, Set<VettingStatus> vettingStatuses) {
       this.name = name;
       this.vettingStatuses = vettingStatuses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="agency_id", unique=true, nullable=false)
    public Integer getAgencyId() {
        return this.agencyId;
    }
    
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agency")
    public Set<VettingStatus> getVettingStatuses() {
        return this.vettingStatuses;
    }
    
    public void setVettingStatuses(Set<VettingStatus> vettingStatuses) {
        this.vettingStatuses = vettingStatuses;
    }




}


