package com.eramaya.eravett.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employer generated by hbm2java
 */
@Entity
@Table(name="employer"
    ,schema="eravett"
)
public class Employer  implements java.io.Serializable {


     private Integer employerId;
     private String name;
     private Set<ProfileEmployer> profileEmployers = new HashSet<ProfileEmployer>(0);
     private Set<VettingOrder> vettingOrders = new HashSet<VettingOrder>(0);

    public Employer() {
    }

    public Employer(String name, Set<ProfileEmployer> profileEmployers, Set<VettingOrder> vettingOrders) {
       this.name = name;
       this.profileEmployers = profileEmployers;
       this.vettingOrders = vettingOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="employer_id", unique=true, nullable=false)
    public Integer getEmployerId() {
        return this.employerId;
    }
    
    public void setEmployerId(Integer employerId) {
        this.employerId = employerId;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employer")
    public Set<ProfileEmployer> getProfileEmployers() {
        return this.profileEmployers;
    }
    
    public void setProfileEmployers(Set<ProfileEmployer> profileEmployers) {
        this.profileEmployers = profileEmployers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employer")
    public Set<VettingOrder> getVettingOrders() {
        return this.vettingOrders;
    }
    
    public void setVettingOrders(Set<VettingOrder> vettingOrders) {
        this.vettingOrders = vettingOrders;
    }




}


