package com.eramaya.eravett.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FileBlob generated by hbm2java
 */
@Entity
@Table(name="file_blob"
    ,schema="eravett"
)
public class FileBlob  implements java.io.Serializable {


     private Integer id;
     private String mimeType;
     private Integer docSize;
     private byte[] blobContent;
     private String fileName;
     private String createdBy;
     private Date createdDate;
     private String updatedBy;
     private Date updatedDate;
     private Set<Profile> profiles = new HashSet<Profile>(0);

    public FileBlob() {
    }

    public FileBlob(String mimeType, Integer docSize, byte[] blobContent, String fileName, String createdBy, Date createdDate, String updatedBy, Date updatedDate, Set<Profile> profiles) {
       this.mimeType = mimeType;
       this.docSize = docSize;
       this.blobContent = blobContent;
       this.fileName = fileName;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.updatedBy = updatedBy;
       this.updatedDate = updatedDate;
       this.profiles = profiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="mime_type", length=128)
    public String getMimeType() {
        return this.mimeType;
    }
    
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    
    @Column(name="doc_size", precision=22, scale=0)
    public Integer getDocSize() {
        return this.docSize;
    }
    
    public void setDocSize(Integer docSize) {
        this.docSize = docSize;
    }

    
    @Column(name="blob_content")
    public byte[] getBlobContent() {
        return this.blobContent;
    }
    
    public void setBlobContent(byte[] blobContent) {
        this.blobContent = blobContent;
    }

    
    @Column(name="file_name", length=100)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="created_by", length=50)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_date", length=29)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    
    @Column(name="updated_by", length=50)
    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="updated_date", length=29)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fileBlob")
    public Set<Profile> getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Set<Profile> profiles) {
        this.profiles = profiles;
    }




}


