package com.eramaya.eravett.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProfileEmployer generated by hbm2java
 */
@Entity
@Table(name="profile_employer"
    ,schema="eravett"
)
public class ProfileEmployer  implements java.io.Serializable {


     private Integer id;
     private Employer employer;
     private Profile profile;
     private String position;

    public ProfileEmployer() {
    }

    public ProfileEmployer(Employer employer, Profile profile, String position) {
       this.employer = employer;
       this.profile = profile;
       this.position = position;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employer_id")
    public Employer getEmployer() {
        return this.employer;
    }
    
    public void setEmployer(Employer employer) {
        this.employer = employer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profile_id")
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }

    
    @Column(name="position")
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }




}


