package com.eramaya.eravett.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name="role"
    ,schema="uam"
)
public class Role  implements java.io.Serializable {


     private String roleId;
     private String roleName;
     private Set<User> users = new HashSet<User>(0);

    public Role() {
    }

	
    public Role(String roleId) {
        this.roleId = roleId;
    }
    public Role(String roleId, String roleName, Set<User> users) {
       this.roleId = roleId;
       this.roleName = roleName;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="role_id", unique=true, nullable=false, length=50)
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    
    @Column(name="role_name")
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="roles")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


