package com.eramaya.eravett.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VettingOrder generated by hbm2java
 */
@Entity
@Table(name="vetting_order"
    ,schema="eravett"
)
public class VettingOrder  implements java.io.Serializable {


     private Integer vettingOrderId;
     private AssetOwner assetOwner;
     private Integer employerId;
     private String poNo;
     private String purpose;
     private Set<Vetting> vettings = new HashSet<Vetting>(0);

    public VettingOrder() {
    }

    public VettingOrder(AssetOwner assetOwner, Integer employerId, String poNo, String purpose, Set<Vetting> vettings) {
       this.assetOwner = assetOwner;
       this.employerId = employerId;
       this.poNo = poNo;
       this.purpose = purpose;
       this.vettings = vettings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vetting_order_id", unique=true, nullable=false)
    public Integer getVettingOrderId() {
        return this.vettingOrderId;
    }
    
    public void setVettingOrderId(Integer vettingOrderId) {
        this.vettingOrderId = vettingOrderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="asset_owner_id")
    public AssetOwner getAssetOwner() {
        return this.assetOwner;
    }
    
    public void setAssetOwner(AssetOwner assetOwner) {
        this.assetOwner = assetOwner;
    }

    
    @Column(name="employer_id")
    public Integer getEmployerId() {
        return this.employerId;
    }
    
    public void setEmployerId(Integer employerId) {
        this.employerId = employerId;
    }

    
    @Column(name="po_no", length=50)
    public String getPoNo() {
        return this.poNo;
    }
    
    public void setPoNo(String poNo) {
        this.poNo = poNo;
    }

    
    @Column(name="purpose", length=500)
    public String getPurpose() {
        return this.purpose;
    }
    
    public void setPurpose(String purpose) {
        this.purpose = purpose;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vettingOrder")
    public Set<Vetting> getVettings() {
        return this.vettings;
    }
    
    public void setVettings(Set<Vetting> vettings) {
        this.vettings = vettings;
    }




}


