package com.eramaya.eravett.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VettingProfile generated by hbm2java
 */
@Entity
@Table(name="vetting_profile"
    ,schema="eravett"
)
public class VettingProfile  implements java.io.Serializable {


     private Integer vettingProfileId;
     private Profile profile;
     private Vetting vetting;
     private String active;
     private String status;
     private Set<VettingStatus> vettingStatuses = new HashSet<VettingStatus>(0);

    public VettingProfile() {
    }

    public VettingProfile(Profile profile, Vetting vetting, String active, String status, Set<VettingStatus> vettingStatuses) {
       this.profile = profile;
       this.vetting = vetting;
       this.active = active;
       this.status = status;
       this.vettingStatuses = vettingStatuses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vetting_profile_id", unique=true, nullable=false)
    public Integer getVettingProfileId() {
        return this.vettingProfileId;
    }
    
    public void setVettingProfileId(Integer vettingProfileId) {
        this.vettingProfileId = vettingProfileId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profile_id")
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vetting_id")
    public Vetting getVetting() {
        return this.vetting;
    }
    
    public void setVetting(Vetting vetting) {
        this.vetting = vetting;
    }

    
    @Column(name="active", length=1)
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }

    
    @Column(name="status", length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vettingProfile")
    public Set<VettingStatus> getVettingStatuses() {
        return this.vettingStatuses;
    }
    
    public void setVettingStatuses(Set<VettingStatus> vettingStatuses) {
        this.vettingStatuses = vettingStatuses;
    }




}


