package com.eramaya.eravett.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vetting generated by hbm2java
 */
@Entity
@Table(name="vetting"
    ,schema="eravett"
)
public class Vetting  implements java.io.Serializable {


     private Integer vettingId;
     private VettingOrder vettingOrder;
     private Date date;
     private Date expiryDate;
     private Set<VettingProfile> vettingProfiles = new HashSet<VettingProfile>(0);

    public Vetting() {
    }

    public Vetting(VettingOrder vettingOrder, Date date, Date expiryDate, Set<VettingProfile> vettingProfiles) {
       this.vettingOrder = vettingOrder;
       this.date = date;
       this.expiryDate = expiryDate;
       this.vettingProfiles = vettingProfiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vetting_id", unique=true, nullable=false)
    public Integer getVettingId() {
        return this.vettingId;
    }
    
    public void setVettingId(Integer vettingId) {
        this.vettingId = vettingId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vetting_order_id")
    public VettingOrder getVettingOrder() {
        return this.vettingOrder;
    }
    
    public void setVettingOrder(VettingOrder vettingOrder) {
        this.vettingOrder = vettingOrder;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=13)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expiry_date", length=13)
    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vetting")
    public Set<VettingProfile> getVettingProfiles() {
        return this.vettingProfiles;
    }
    
    public void setVettingProfiles(Set<VettingProfile> vettingProfiles) {
        this.vettingProfiles = vettingProfiles;
    }




}


